name: Build

on: [push, pull_request]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependancies
        run: "npm i"
      - name: Compile Typescript
        run: "tsc"
  compile_linux:
    name: "Compile for linux"
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: "Compile for Linux"
        run: "npm run compile-linux"
  compile_macos:
    name: "Compile for macos"
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: "Compile for MacOS"
        run: "npm run compile-macos"
  compile_win:
    name: "Compile for win"
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: "Compile for Windows"
        run: "npm run compile-win"
